apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: tags-service-prod
nameSuffix: -prod

commonLabels:
  environment: prod

replicas:
- name: tags-service
  count: 2
