apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: notes-service-prod
nameSuffix: -prod

commonLabels:
  environment: prod

replicas:
- name: notes-service
  count: 2
