apiVersion: v1
kind: Service
metadata:
  name: notes-service
  labels:
    app: notes-service
spec:
  type: ClusterIP
  selector:
    app: notes-service
  ports:
  - port: 80
    targetPort: 3003
    protocol: TCP
    name: http
