apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

namespace: api-gateway-prod
nameSuffix: -prod

commonLabels:
  environment: prod

replicas:
- name: api-gateway
  count: 2
