apiVersion: v1
kind: Service
metadata:
  name: tags-service
  labels:
    app: tags-service
spec:
  type: ClusterIP
  selector:
    app: tags-service
  ports:
  - port: 80
    targetPort: 3004
    protocol: TCP
    name: http
